version: '3.8'

services:
  fastapi-app:
    image: ${DOCKER_USERNAME}/fastapi-demo:latest
    container_name: fastapi-app
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - fastapi-app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email your-email@example.com -d my-ci-cd-pipeline.solcraftdevs.com --agree-tos

networks:
  app-network:
    driver: bridge