name: Test FastAPI App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test if app starts
      run: |
        python -c "from main import app; print('App imported successfully!')"
    
    - name: Build Docker image
      run: |
        docker build -t my-fastapi-app .
    
    - name: Test Docker container
      run: |
        docker run -d -p 8000:8000 --name test-container my-fastapi-app
        sleep 5
        curl -f http://localhost:8000/health || exit 1
        docker stop test-container